apiVersion: v1
kind: Pod
metadata:

  labels:
    run: test
  name: test
spec:
  restartPolicy: Never
  containers:
  - image: syedwahajali/robusta_check
    name: test
    resources: {}
  dnsPolicy: ClusterFirst
  
status: {}
